name = "CasualPlots"
uuid = "96609e94-6212-48a9-9561-4cd28ba001d1"
authors = ["Eben60"]
version = "0.4.0-alpha"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Electron = "a1bb12fb-d4d1-54b4-b10a-ee7951ef7ad3"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Hyperscript = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[weakdeps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[extensions]
ReadCSV_Ext = "CSV"
ReadXLSX_Ext = "XLSX"

[compat]
AlgebraOfGraphics = "0.12"
Bonito = "4.1"
CSV = "0.10"
CairoMakie = "0.15"
ColorSchemes = "3.31"
DataFrames = "1.8"
Dates = "1.10"
Electron = "6.1"
FilePathsBase = "0.9"
Hyperscript = "0.0.5 - 0.1"
NativeFileDialog = "0.2.1"
Observables = "0.5"
PrecompileTools = "1.2"
Unitful = "1.25"
WGLMakie = "0.13"
XLSX = "0.10"
julia = "1.10"
