name = "CasualPlots"
uuid = "96609e94-6212-48a9-9561-4cd28ba001d1"
version = "0.0.4"
authors = ["Eben60"]

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Electron = "a1bb12fb-d4d1-54b4-b10a-ee7951ef7ad3"
Hyperscript = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
Bonito = "4.1"
ColorSchemes = "3.31.0"
DataFrames = "1.8"
Electron = "6.1"
Unitful = "1.25"
julia = "1.10"
